# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-19 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KirrURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name': 'KirrURL',
                'verbose_name_plural': 'KirrURL',
            },
        ),
    ]
