# Generated by Django 2.2.12 on 2020-05-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
